### ISSUE TITLE
Can't install this from yarn

### ISSUE THREAD

**Issue by msuntharesan** [bluebirds-blue-jay/access-control#11]
Trying to install throws `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
I think it's because you have circular dependency between `@bluejay/collection` and `@bluejay/utils `

**Comment by SylvainEstevez** [comment]
Thanks for opening this issue @vanthiyathevan. Unfortunately removing the dependency on either side would break quite some stuff :(

I'm assuming you can't use `npm` @vanthiyathevan? `npm` does not have this issue hence why it never came up in one year of usage I guess.

Meantime there is this `yarn` issue that's open: https://github.com/yarnpkg/yarn/issues/6279

Will follow the development in there and see what to do next 🤞 . Sorry but I can't think of any workaround...

**Comment by vanthiyathevan** [comment]
Thanks for the issue on yarn. We rely on yarn workspaces and monorepo for our project, so we can't use npm.

**Comment by SylvainEstevez** [comment]
The cyclic dependency issue is solved in `v4` (beta at the time of writing).
