### ISSUE TITLE
Attach more data besides returnedAttributes to permissions

### ISSUE THREAD

**Issue by broom9** [bluebirds-blue-jay/access-control#20]
In my understanding, the "returnedAttributes" is basically a piece of custom data that can be attached to a permission statement. And it can be retrieved if the permission statement is used to grant a subject to access a resource.

Is there a way to attach more custom data besides the "returnedAttributes" attribute to permission? There are other cases besides the "returnedAttributes" case.

For example, if a user can only see books published in his own country, we might want to attach a "where books.country = user.country" condition when listing books for a user. It would be good to define this condition (and potentially other more complicated conditions) on the permission to grant user read permission to the "book" resource, and retrieve these conditions when listing books.

Such additional info on a "Permission" doesn't fit in the "returnedAttributes" concept, but can be useful.

**Comment by SylvainEstevez** [comment]
Very good suggestion. I guess the store would need to hold a generic to define the returned types. Should be easy to do, although I don’t have time right now. I’ll have a look later when I can but feel free to make a PR meantime!
