### ISSUE TITLE
Value Associated with Role?

### ISSUE THREAD

**Issue by jcfergus** [bluebirds-blue-jay/access-control#32]
First off, thanks for this library - it is exactly what I was looking for, and has excellent documentation.   

I'm trying to figure out if there's a way to associate a value with a role.   For example, in the system I'm working on, a user can have different privileges for different organizations, so I'd like to be able to say something like: `addRoleToSubject(subject, roles.ORGADMIN, organizationId), and then build my policies appropriately.   

Any suggestions?

**Comment by SylvainEstevez** [comment]
Hi @jcfergus, can you share more context on your use case? Do you know which organization(s) the subject is admin of at runtime?

If yes, then I'd suggest you add some conditions to your permissions. Quick example:

```typescript
class MySubject extends Subject<{ id: number, role: string, organizationId: number }> {
    public getPrincipal() {
        return this.get('id');
    }
}


const store = new MemoryStore();

store.addPermissionToRole(Role.ORGADMIN, {
    id: 'SomePermission',
    effect: PermissionEffect.ALLOW,
    resource: 'foo',
    action: 'bar',
    condition: {
        numberEquals: {
            simpleValue: {
                '{{{environment.organizationId}}}': '{{{subject.organizationId}}}'
            }
        }
    }
});
```

See here for dynamic permissions: https://github.com/bluebirds-blue-jay/access-control#condition-variables

Alternatively, you can create your own store:

```typescript
class MyStore implements IStore {
    public addRoleToSubject(subjectOrPrincipal: TSubjectOrPrincipal, role: string, organizationId: number) {
        // ... your logic
    }

    public getPermissionsForSubject(subject: MySubject): TPermission[] {
        // This is the only method required for the IStore interface.
    }
}
```

See here for custom stores: https://github.com/bluebirds-blue-jay/access-control#stores

Let me know if that helps! :)

**Comment by jcfergus** [comment]
The set of organizations that a user may have roles in is part of the user's record in the database, and could change at any time, without the app being restarted.   I think the custom store is probably the best answer.   Thanks for the quick response!
