### ISSUE TITLE
Would this PR be welcomed here?

### ISSUE THREAD

**Issue by vegerot** [bluebirds-blue-jay/access-control#33]
Worked on addressing https://github.com/onury/accesscontrol/issues/93 for a while, and opened https://github.com/onury/accesscontrol/pull/94 before realizing it was largely abandoned.  Would that PR be approved here?

I [read](https://github.com/onury/accesscontrol/issues/84#issuecomment-629070343) this repo is a fork of that repo, so hopefully it would not be too hard to include

**Comment by SylvainEstevez** [comment]
@vegerot This repo is not based on onury’s one at all. We just took a bit of inspiration from it. Feel free to propose any non breaking change you’d like to include.
