### ISSUE TITLE
No Doc for Persistence Layer

### ISSUE THREAD

**Issue by cyberbird20** [bluebirds-blue-jay/access-control#9]
In the Readme there is this lines

> We'll then need to tell Bluejay where to look for permissions. AccessControl comes package with a built-in MemoryStore that allows you to manage permissions in memory. We'll cover persistent stores later in this documentation.

But it not anywhere in the docs. Please help thanks. MongoDB Layer will be helpful

**Comment by SylvainEstevez** [comment]
Thanks for opening this issue @cyberbird20. I'll make my best to document persistent stores by the end of the week.

Meantime if you want to progress, a `store` simply needs to implement the [`IStore`](https://github.com/bluebirds-blue-jay/access-control/blob/master/src/interfaces/store.ts#L4) interface, which contains a single method.

**Comment by SylvainEstevez** [comment]
@cyberbird20 Sorry it took so long but the docs are no up: https://github.com/bluebirds-blue-jay/access-control#stores

You'll also find an example implementation for MongoDB. Let me know if I can help with anything else!
